config/routes.rb
Rails.application.routes.draw do
  resources :boards
  root 'boards#new'
  get '/all', to: 'boards#all', as: 'all'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :width, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :height, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :mines, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :name, presence: true
  validate :mines_within_board_size

  scope :recent_boards, -> { order(created_at: :desc) }

  private

  def mines_within_board_size
    total_cells = width.to_i * height.to_i

    return unless mines.to_i > total_cells

    errors.add(:mines, 'Cannot be greater than the total number of cells on the board')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  ITEMS_PER_PAGE = 10

  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @boards = filtered_boards.limit(10)
  end

  def all
    @pagy, @boards = pagy(filtered_boards, items: ITEMS_PER_PAGE)
  end

  def show; end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)

    return render :new, status: :unprocessable_entity unless @board.valid?

    minesweeper_generator = MinesweeperGeneratorService.new(@board.width, @board.height, @board.mines)
    @board.data = minesweeper_generator.call

    if @board.save
      redirect_to @board, notice: 'Board was successfully generated'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @board.update(board_params)
      redirect_to @board, notice: 'Board was successfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path, status: :see_other
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def filtered_boards
    boards = Board.recent_boards

    if params[:name_cont].present?
      boards = boards.where('name ILIKE ?', "%#{params[:name_cont]}%")
    end

    if params[:email_cont].present?
      boards = boards.where('email ILIKE ?', "%#{params[:email_cont]}%")
    end

    boards
  end

  def board_params
    params.require(:board).permit(:name, :email, :width, :height, :mines)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<%= form_tag(boards_path, method: :get, class: "mb-3") do %>
  <div class="d-flex align-items-end">
    <div class="mb-2">
      <%= label_tag :name_cont, "Board Name contains", class: "form-label" %>
      <%= text_field_tag :name_cont, params[:name_cont], class: "form-control" %>
    </div>

    <div class="mb-2 ms-3">
      <%= label_tag :email_cont, "Creator Email contains", class: "form-label" %>
      <%= text_field_tag :email_cont, params[:email_cont], class: "form-control" %>
    </div>

    <button type="submit" class="btn btn-primary button-filter btn-sm ms-3">Filter</button>
  </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created by</th>
      <th>Created at</th>
      <th>WIDTH</th>
      <th>HEIGHT</th>
      <th>MINES</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= link_to board.name, board %></td>
        <td><%= board.email %></td>
        <td><%= board.created_at.strftime("%B %d, %Y, %H:%M") %></td>
        <td><%= board.width %></td>
        <td><%= board.height %></td>
        <td><%= board.mines %></td>
        <td class='d-flex'>
          <%= link_to 'Edit', edit_board_path(board), class: 'btn btn-primary btn-sm mr-2 me-2', remote: true %>
          <%= link_to "Destroy", board_path(board), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                }, class:'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true, html: { class: "form" }) do |form| %>
  <% if @board.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading">Validation errors occurred:</h4>
      <ul>
        <% @board.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :width, class: "form-label" %>
    <%= form.number_field :width, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :height, class: "form-label" %>
    <%= form.number_field :height, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :mines, class: "form-label" %>
    <%= form.number_field :mines, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <%= form.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "List Recent Boards", boards_path, class: "text-secondary lh-lg float-end" %>
<% end %>

app/views/boards/all.html.erb
<div class="container w-75">
  <h1>All Boards</h1>

  <%= render partial: 'board', locals: { boards: @boards, pagy: @pagy } %>

  <div class='d-flex justify-content-between'>
    <p><%== pagy_info(@pagy) %></p>
    <%== pagy_bootstrap_nav(@pagy, items: 10) %>
  </div>

  <%= link_to "Back to Recent Boards", boards_path, class: "btn btn-secondary" %>
</div>

app/views/boards/edit.html.erb
<div class="container">
  <h1 class='text-center'>Edit Board</h1>
  <%= render 'form' %>
</div>

app/views/boards/index.html.erb
<div class="container w-75">
  <h1 class="mb-4 text-center">Recent Boards</h1>

  <%= render partial: 'board', locals: { boards: @boards } %>

  <div class="mt-3">
    <%= link_to "Show All Boards", all_path, class: "text-secondary" %>
  </div>

  <%= link_to "New Board", new_board_path, class: "btn btn-primary mt-3" %>
</div>

app/views/boards/new.html.erb
<div class="container">
  <h1 class='text-center'>Create New Board</h1>
  <%= render 'form' %>
</div>

app/views/boards/show.html.erb
<div class='container' data-controller="minesweeper" data-minesweeper-height="<%= @board.height %>" data-minesweeper-width="<%= @board.width %>" data-minesweeper-mines="<%= @board.mines %>">
  <h1><%= @board.name %></h1>
  <p>Created by: <%= @board.email %></p>
  
  <p class="board-details fw-i">
    Height: <%= @board.height %>;
    Width: <%= @board.width %>;
    Mines: <%= @board.mines %>
  </p>
  
  <%= link_to "Back to Boards", boards_path, class: "text-secondary" %>

  <div id="board" data-target="minesweeper.board"></div>

  <button id='playAgainBtn' data-action="minesweeper#playAgain" style="display: none;" class='btn btn-primary mt-3'>Play Again</button>
</div>

app/views/boards/test.html.erb
<div data-controller="test">
  <h2>helllo</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>